version: 2

build:
    os: ubuntu-lts-latest
    tools:
        python: 'latest'
        rust: 'latest'
        # You can also specify other tool versions:
    jobs:
        post_install:
            # Install with docs extras
            - python -m pip install uv
            - UV_PROJECT_ENVIRONMENT=$READTHEDOCS_VIRTUALENV_PATH uv sync

        build:
            html:
                - zensical build

        post_build:
            - mkdir -p $READTHEDOCS_OUTPUT/html/
            - cp --recursive site/* $READTHEDOCS_OUTPUT/html/

python:
    install:
        - method: pip
          path: .
